server:
  port: 8080
  servlet:
    context-path: /
logging:
  file:
    path: ./runtime.log
  level:
    root: debug

debug: true

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/warehouse?characterEncoding=UTF-8&amp;characterSetResults=UTF-8&amp;serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.nanami52.warehouse.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
